services:
  metabase-h2:
    image: metabase/metabase:v0.41.5
    # Host:Container
    ports:
      - "3000:3000"
  metabase-mysql:
    image: metabase/metabase:v0.41.5
    # Host:Container
    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 3306
      MB_DB_USER: root
      MB_DB_PASS: superuser
      MB_DB_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:5.7.44 # Very old - change to 8.4
    restart: always
    #This avoids error serverRsaPublicKeyFile not set on metabase
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: superuser        # Set the MySQL root password
      MYSQL_DATABASE: metabase              # Create database
      MYSQL_USER: metabase                  # Create a non-root user
      MYSQL_PASSWORD: metabase              # Set the password for the non-root user
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - mysql_data:/var/lib/mysql
  metabase-postgres:
    image: metabase/metabase:v0.41.5
    ports:
      - "3002:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: postgres #Default auto created db
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: superuser
      MB_DB_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:15
    restart: always
    user: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres # Default user
      POSTGRES_PASSWORD: superuser
      POSTGRES_DB: postgres # Default db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
  mysql_data:

