services:
  metabase-mysql:
    image: metabase/metabase:v0.41.5
    # Host:Container
    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: mydb
      MB_DB_PORT: 3306
      MB_DB_USER: root
      MB_DB_PASS: superuser
      MB_DB_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:5.7.44 # Very old - change to 8.4
    #This avoids error serverRsaPublicKeyFile not set on metabase
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: superuser        # Set the MySQL root password
      MYSQL_DATABASE: mydb                  # Create a default database
      MYSQL_USER: myuser                    # Create a non-root user
      MYSQL_PASSWORD: mypwd                 # Set the password for the non-root user
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ./mysql-data

